#ifndef OSWITCHOBJECT2_H__
#define OSWITCHOBJECT2_H__

enum
{
	SWITCHOBJECT2_CHILD      = 10000,
	SWITCHOBJECT2_PARENTLINK = 10001,
	SWITCHOBJECT2_RENAME     = 10002,

	SWITCHOBJECT2_DUMMY_ELEMENT_
};

#endif // OSWITCHOBJECT2_H__
