CONTAINER oswitchobject2
{
	NAME oswitchobject2;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG SWITCHOBJECT2_CHILD { CYCLE {} }
		LINK SWITCHOBJECT2_PARENTLINK { ACCEPT { Obase; } }
		BOOL SWITCHOBJECT2_RENAME {}
	}
}
